### PR TITLE
Remove ARMv6

### PR DESCRIPTION
**Pull request by joshua-pe**
Not a supported arch on home assistant. If left, i get this error

```
Can't read /data/addons/git/ae9861ff/photons-interactor/config.json: does not match regular expression for dictionary value @ data['image']. Got 'delfick/lifx-photons-interactor-homeassistant:0.8.5'
value must be one of ['aarch64', 'amd64', 'armhf', 'armv7', 'i386'] @ data['arch'][1]. Got 'armv6'
```

### CODE REVIEW

**Comment by delfick** [comment]
perhaps it's meant to be armhf then. I was confused because the docker command I use specifies `          platforms: linux/386,linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6 `

**Comment by delfick** [comment]
Thanks. I've updated the repo outside of your PR and updated the docker image to have the same in it's label.

**Comment by joshua-pe** [comment]
That removes that error, but this one arises. 
```
Can't read /data/addons/git/ae9861ff/photons-interactor/config.json: does not match regular expression for dictionary value @ data['image']. Got 'delfick/lifx-photons-interactor-homeassistant:0.8.5'
```

**Comment by Final-Hawk** [comment]
Probably just try without the delfick/ at the start

**Comment by joshua-pe** [comment]
Oh @delfick just remove the version at the end of the image. (:0.8.5)

**Comment by delfick** [comment]
maybe it adds it from the version in the config.json. try now

**Comment by delfick** [comment]
when you use the addon, as a user are you able to add a lifx.yml into the /data it mounts?

**Comment by joshua-pe** [comment]
That seems to work great. The database is properly mounted and works after a reboot. 

Yes i can add lifx.yml and change the options. Great!

**Comment by joshua-pe** [comment]
You could get the options from options.json instead of lifx.yml so you could use this

https://developers.home-assistant.io/docs/add-ons/configuration#options--schema

But really not needed. Something i could look into later.

**Comment by delfick** [comment]
I think the options.json is defined by me as a provider of the addon rather than from the user using the addon

Ok, I'll add a page to the docs about using home assistant.

**Pull request closed without merging**
